// flow-typed signature: 36b1f48d7379228815f873bcb7d5fb42
// flow-typed version: <<STUB>>/box-muller_v^0.0.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'box-muller'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'box-muller' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'box-muller/index' {
  declare module.exports: $Exports<'box-muller'>;
}
declare module 'box-muller/index.js' {
  declare module.exports: $Exports<'box-muller'>;
}
